### ISSUE TITLE
Using both pages and blocks doesn't work or make sense

### ISSUE THREAD

**Issue by robbieaverill** [dnadesign/silverstripe-elemental-userforms#10]
In the context where you're using elemental and you've installed this module, you can either add a Form block to an existing page, or create a User Defined Form page (userforms module).

If you create a User Defined Form page and complete the details for it the way you would without using elemental, the form doesn't render onto the page because the original page content has been replaced.

Perhaps we need to disable the User Defined Form page type in this context, so you have to add a Form block to a page rather.

**Comment by robbieaverill** [comment]
cc @clarkepaul and @sachajudd for UX feedback

**Comment by clarkepaul** [comment]
Yup that makes sense. The only other useful way would be to have a form page without the content blocks enabled on it (the dev might want to set up custom fixed fields?), but then again this could be achieved by setting up a page with fixed blocks (not changeable/deletable etc).

**Comment by robbieaverill** [comment]
So perhaps we should ship this module with config that disables blocks on UserDefinedForm page types?

**Comment by adrexia** [comment]
Historically, we've applied elemental to a pagetype that extends Page, and not Page itself to avoid this sort of conflict.

**Comment by robbieaverill** [comment]
So perhaps this is something that should be documented clearly, rather than being treated as a bug?

**Comment by pitchandtone** [comment]
Yes please. This module breaks things pretty quickly if you apply to page.
