### ISSUE TITLE
Two Forms on One Page

### ISSUE THREAD

**Issue by asecondwill** [dnadesign/silverstripe-elemental-userforms#20]
If i add two UserForm elements to a page, the second form has it's fields hidden.  Seems like it is thinking the second form is actually a second page of one form. 

Markup responsible for hiding the fields:

````
<div id="EditableFormStep_0f006" class="form-step field CompositeField userformsstep" data-title="First Page" aria-hidden="true" style="display: none;">
````

**Comment by asecondwill** [comment]
Also, if you submit the page, the Thanks message shows on both forms.

**Comment by robbieaverill** [comment]
Thanks for reporting. It seems like there are two issues here:

* Likely the userforms javascript is not ready to handle multiple forms
* We need to assign the backend form validation messages to a specific form instance

**Comment by asecondwill** [comment]
Any Likely ETA on this?  Early 2018?

**Comment by asecondwill** [comment]
Thinking about this, it's a problem with UserForms however two of them end up on a page together.  

EG,  if I pull one into the footer, say a NewsLetter signup form - it will not show it's fields on any UserForm page.  

Should I open a ticket over in userforms?  

https://github.com/silverstripe/silverstripe-userforms/issues

**Comment by robbieaverill** [comment]
Yeah if you don't mind that'd be cool

**Comment by asecondwill** [comment]
They are saying won't fix.  

That means that every little form required in a footer etc needs to be hard coded.  

not great at all.

**Comment by robbieaverill** [comment]
Hi @asecondwill, we will fix this. The comment on that userforms issue was from when this feature didn't exist - it does now.

**Comment by robbieaverill** [comment]
Linked issues: dnadesign/silverstripe-elemental#176 and silverstripe/silverstripe-userforms#543

**Comment by NightJar** [comment]
Already seemed to work pretty welll, but tidy up fixes in https://github.com/silverstripe/silverstripe-userforms/pull/715

**Comment by asecondwill** [comment]
This is great.  thanks.  Ill test this week on the site where this came up. thanks!
