### ISSUE TITLE
Error when adding an EmailRecipient record

### ISSUE THREAD

**Issue by gheggie** [dnadesign/silverstripe-elemental-userforms#23]
In `EmailRecipient::getCMSFields()` the line `$form = $this->getFormParent();` returns null (so `$form->ID` on the next line returns an error). I'm not entirely sure how ElementForm works in the CMS though.

**Comment by andrewandante** [comment]
@gheggie can you confirm whether https://github.com/silverstripe/silverstripe-userforms/pull/716 has fixed this issue?

**Comment by jsirish** [comment]
@andrewandante we're using userforms 5.0.x-dev and are having this issue as well.

**Comment by andrewandante** [comment]
@jsirish could you confirm the commit you are using of 5.0.x-dev? Just to make sure I'm testing what you are using 👍

**Comment by jsirish** [comment]
@andrewandante sure thing - 20570ef1

Thanks for looking into this!

**Comment by andrewandante** [comment]
Cheers, right up to date. Will have a go through it tomorrow.

**Comment by andrewandante** [comment]
There's a PR to fix this here: https://github.com/silverstripe/silverstripe-userforms/pull/722

It means that only the TextFields are present on creation of the record, but on save the dropdowns will populate.

Ideally, we can hook into the Gridfield list and populate them that way, but haven't quite figured that one out yet.

**Comment by NightJar** [comment]
Thanks @andrewandante !
