### ISSUE TITLE
Install on SS3.5

### ISSUE THREAD

**Issue by digitall-it** [dnadesign/silverstripe-elemental-userforms#24]
I would like to install it on SS3.5, but the latest supporting release is not tagged or branched. Should I link to a specific commit ID?

**Comment by robbieaverill** [comment]
Hi @digitall-it, this module is SS4 only unfortunately. You could fork it and adjust earlier commits in the history to work with your project.

**Comment by digitall-it** [comment]
Thank you for the prompt response, and for the very good work with Elemental.

I really like that the module community is galloping fast toward SS4.0. It would be interesting to semver tag it (maybe directly as as v4) to make it future proof.

**Comment by robbieaverill** [comment]
Thanks for the kind words 😃  you can currently use `1.x-dev`, and this will stabilise through to 1.0.0 as the module progresses.

**Comment by digitall-it** [comment]
I forked the project and made it work on SS3 with minimal changes.

Here is the suggested course of action:

- create a **ss3** branch based on **dev-master**
- I wil PR to that branch with tags in the 0.x range

This way we will continue to follow **semver**.
