### ISSUE TITLE
Block default JS or CSS

### ISSUE THREAD

**Issue by clodeindustrie** [dnadesign/silverstripe-elemental-userforms#25]
Not sure if it's supposed to be obvious, but it might be interesting to add to the doc that if you want to block the default JS and CSS from being required you need to set the flag to the `ElementForm` class.

```
DNADesign\ElementalUserForms\Model\ElementForm:
  block_default_userforms_js: true
```

**Comment by robbieaverill** [comment]
Thanks for pointing this out. Would you like to make a PR to add it to the docs?

**Comment by clodeindustrie** [comment]
Here you go https://github.com/dnadesign/silverstripe-elemental-userforms/pull/26
