### ISSUE TITLE
Disable inline editing by default

### ISSUE THREAD

**Issue by brynwhyman** [dnadesign/silverstripe-elemental-userforms#33]
With inline editing to be implemented in `dnadesign/silverstripe-elemental 4.0` we should disable inline editing by default for the userform block. Instead the user will be directed to the GridFeildDetailForm and have a full screen to create the block.

**Comment by robbieaverill** [comment]
PR at https://github.com/dnadesign/silverstripe-elemental-userforms/pull/34

**Comment by ScopeyNZ** [comment]
Closed in #34
