### ISSUE TITLE
Multiple form elements on one page all display thank you message after one is submitted

### ISSUE THREAD

**Issue by michalkleiner** [dnadesign/silverstripe-elemental-userforms#50]
The presence of the /finished/#uff in the URL makes all UDF elements on the same page display the Thank you message even though only one was submitted.

## PRs
- https://github.com/dnadesign/silverstripe-elemental-userforms/pull/83

**Comment by digitall-it** [comment]
I propose to change the URL to /finished/#uff=ID and check for that. If the fragment is grepped (i.e. the URL checked for the presence of the substring hashmark uff), then legacy code should continue to work. New code could instead discern for what form has been submitted.

**Comment by michalkleiner** [comment]
@digitall-it the anchor fragment is not passed to the server, so it can't use it for any logic.

**Comment by digitall-it** [comment]
Fine. Can't then any variable be passed back to the frontend in the get URL to be used by javascript to locate and scroll to the right form? For example, surely the server knows the Form ID, and that can at least be passed back, like `/finished/#uff?formID=ID` (or what the correct syntax is). Then, it's a matter for the frontend programmer to add a `data-formid="123"` in the template to match it in the frontend.

**Comment by GuySartorelli** [comment]
PR merged. This will be automatically tagged by GitHub Actions.
