### ISSUE TITLE
Form submission issue

### ISSUE THREAD

**Issue by Thiyagarajantender** [dnadesign/silverstripe-elemental-userforms#59]
Getting below error when use form inside list block.

Fatal error: Element $id not found for this page in F:\xampp7\htdocs\4es-git\vendor\dnadesign\silverstripe-elemental\src\Extensions\ElementalContentControllerExtension.php on line 47

Notice: Undefined index: args in F:\xampp7\htdocs\4es-git\vendor\silverstripe\framework\src\Dev\Backtrace.php on line 216

Notice: Trying to access array offset on value of type null in F:\xampp7\htdocs\4es-git\vendor\silverstripe\framework\src\Dev\Backtrace.php on line 216

Please adviceto overcome this issue

**Comment by GuySartorelli** [comment]
Closing as a duplicate of https://github.com/dnadesign/silverstripe-elemental-userforms/issues/27
