### ISSUE TITLE
v4: Controls overlap form fields

### ISSUE THREAD

**Issue by chrispenny** [dnadesign/silverstripe-elemental-userforms#71]
Using the latest from the `4.0` branch (https://github.com/dnadesign/silverstripe-elemental-userforms/commit/04282b7cb930be9c16c6f20b534df2542cf1b30c)

![Screen Shot 2023-04-05 at 1 05 16 PM](https://user-images.githubusercontent.com/505788/229955588-743bf41a-22b4-49f0-91a8-619f8e67a857.png)

The issue does not exist when using a `UserDefinedForm` page from Userforms.

## PRs
- https://github.com/silverstripe/silverstripe-userforms/pull/1294

**Comment by UndefinedOffset** [comment]
I'm seeing this on the 3.2.1 release as well with userforms 5.14.2

**Comment by GuySartorelli** [comment]
PR merged. It will be automatically tagged by GitHub actions.
